### PR TITLE
Major updates for STT and TTS

### PR DESCRIPTION
**Pull request by mihui**
- Corrected wrong data sending mechanism by adding list of audio data with different markers
- Refactored TTS by removing TTSUtility class
- Refactored Base configuration class by changing class name and abstracted token and its providers
- Added back TTS delegates
- Added more configurations and opt-out parameter
- Fixed crash issues for both of STT and TTS
- Added onData in delegate in order to capture the raw data and store for STT
- Updated out-of-date README

### CODE REVIEW

**Comment by nacho4d** [comment]
@mihui can you rebase this branch? It says "This branch has conflicts that must be resolved"

**Comment by mihui** [comment]
@nacho4d i see, I though it can be merged :P

**Comment by nacho4d** [comment]
@mihui IMO I think it is better and faster to do various smalls pull requests.

**Comment by mihui** [comment]
@nacho4d yes, agree. I am thinking about move these updates out of this repo or branch, because I did a lots of updates for both of iOS and Android, but they actually need a lot of time to review. Also because these repos are being deprecated. On the other hand, I can clone these repos and add features base on current code piece by piece not like this, really my bad. :)

**Pull request closed without merging**
